### ISSUE TITLE
Should this show Rev B PCB Layout?

### ISSUE THREAD

**Issue by crnorris** [adafruit/Adafruit-Teensy-3.x-Feather-Adapter-PCB#1]
PCB Layout appears to show revision A, with VBAT on the Teensy board incorrectly connected to VBAT on the Feather board. Recommend also clarifying whether the VIN - VUSB link should be cut (presumably not).

**Comment by ladyada** [comment]
@kattni please add `Development\Dev Boards\Feather Teensy3\Rev B`

**Comment by kattni** [comment]
Added!
